version: '3'

services:
  node-red:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    networks:
      - network
    volumes:
      - node_red_data:/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-red

networks:
  network:
    driver: bridge

volumes:
  node_red_data:
    driver: local
